export const PERMISSIONS = {
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',
  GESTIONAR_ROLES: 'GESTIONAR_ROLES',
  VER_DASHBOARD: 'VER_DASHBOARD',
  GESTIONAR_PACIENTES: 'GESTIONAR_PACIENTES',
  GESTIONAR_DOCTORES: 'GESTIONAR_DOCTORES',
  GESTIONAR_CITAS: 'GESTIONAR_CITAS',
  VER_CITAS: 'VER_CITAS',
  GESTIONAR_SOLICITUDES: 'GESTIONAR_SOLICITUDES',
  GESTIONAR_CATALOGOS: 'GESTIONAR_CATALOGOS',
  VER_CONSULTAS: 'VER_CONSULTAS',
  VER_PACIENTES: 'VER_PACIENTES',
  VER_DOCTORES: 'VER_DOCTORES',
  VER_SOLICITUDES: 'VER_SOLICITUDES',
  VER_ROLES: 'VER_ROLES',
  VER_USUARIOS: 'VER_USUARIOS',
  VER_CATALOGOS: 'VER_CATALOGOS',
  GESTIONAR_CONSULTAS: 'GESTIONAR_CONSULTAS',
  VER_HORARIOS: 'VER_HORARIOS',
  GESTIONAR_HORARIOS: 'GESTIONAR_HORARIOS',
  VER_CONFIGURACIONES: 'VER_CONFIGURACIONES',
  GESTIONAR_CONFIGURACIONES: 'GESTIONAR_CONFIGURACIONES',
  EDITAR_ROLES: 'EDITAR_ROLES',
  ELIMINAR_ROLES: 'ELIMINAR_ROLES'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];