export const PERMISSIONS = {
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',
  GESTIONAR_ROLES: 'GESTIONAR_ROLES',
  VER_DASHBOARD: 'VER_DASHBOARD',
  GESTIONAR_PACIENTES: 'GESTIONAR_PACIENTES',
  GESTIONAR_DOCTORES: 'GESTIONAR_DOCTORES',
  GESTIONAR_CITAS: 'GESTIONAR_CITAS',
  VER_CITAS: 'VER_CITAS',
  GESTIONAR_SOLICITUDES: 'GESTIONAR_SOLICITUDES',
  GESTIONAR_CATALOGOS: 'GESTIONAR_CATALOGOS',
  VER_CONSULTAS: 'VER_CONSULTAS'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];